### ISSUE TITLE
Hay lógica repetida

### ISSUE THREAD

**Issue by josibuttazzoni** [alu654/pdp#1]
Acá https://github.com/alu654/pdp/blob/90ec0796fbc060f2d483a338730ff1a8824855a3/correcciontp3.hs#L23
y acá https://github.com/alu654/pdp/blob/90ec0796fbc060f2d483a338730ff1a8824855a3/correcciontp3.hs#L28

Fijate que en las dos funciones modificás el dinero del participante. Podrías delegar en una nueva función que fuera, por ejemplo, cambiarDinero que reciba un jugador y una cantidad de dinero, y te devuelva el nuevo jugador con el valor modificado. De paso, te permitiría usar composición

**Comment by alu654** [comment]
estas estan corregidas!
