### ISSUE TITLE
¿Funciona esto?

### ISSUE THREAD

**Issue by josibuttazzoni** [alu654/pdp#11]
https://github.com/alu654/pdp/blob/4b1a28307b69c05fb553af6140f096811073a085/correcciontp3.hs#L53

https://github.com/alu654/pdp/blob/4b1a28307b69c05fb553af6140f096811073a085/correcciontp3.hs#L76

Pensá que lo que vos querés que haga esAccUOferente es que te devuelva verdadero en caso de que su táctica sea alguna de esas dos. En este caso, en ningún momento estás verificando que su táctica sea esa.

**Comment by alu654** [comment]
listo!

**Comment by josibuttazzoni** [comment]
Bien, ahora funciona, pero, si leo esDe no me da mucha idea de la condición que tiene que cumplir el participante

**Comment by alu654** [comment]
listo!
