### ISSUE TITLE
Lógica repetida

### ISSUE THREAD

**Issue by josibuttazzoni** [alu654/pdp#3]
https://github.com/alu654/pdp/blob/90ec0796fbc060f2d483a338730ff1a8824855a3/correcciontp3.hs#L44

Fijate que podes mejorar esta función usando la que te dije que hagas en #1 .

**Comment by alu654** [comment]
esta no se como hacerla, ya que resta el dinero de la propiedad y si pongo (-) me da error...

**Comment by josibuttazzoni** [comment]
Podés usar `subtract`. (Mirá #9)
